export const labels = {
  projectInfo: {
    projectName: 'Project Name',
    projectOwner: 'Project Owner',
    projectContact: 'Project Contact',
    projectLandingPage: 'Landing Page',
    projectRepository: 'Repository',
    programmingLanguage: 'Programming Language',
    openSourceLicense: 'Open Source License',
    cdiscStandards: 'CDISC Standards',
    agreeWithCdiscCodeOfEthics: 'Agree With CDISC Code Of Ethics',
    projectMaturity: 'Maturity',
    user: 'User',
    logoUrl: 'LogoUrl',
  },
  detailedDescription: {
    problem: 'Problem',
    solution: 'Solution',
    openSourceConsiderations: 'Open Source Considerations',
    maintenanceModel: 'Maintenance Model',
    projectSize: 'Project Size',
    contributors: 'Contributors',
    users: 'Users',
    preRequisites: 'Pre-Requisites',
    projectServiceOptions: 'Project Service Options',
    sponsors: 'Sponsors',
    goalsObjectives: 'Goals Objectives',
    communications: 'Communications',
    additonalInformation: 'Additonal Information',
  },
};
